[package]
name = "picture_vault"
version = "0.1.0"
authors = ["Baschdl578 <remailer1@yahoo.de>"]

[dependencies]
image = "0.17"
rexiv2 = "0.5"
lazy_static = "0.2"
tiny_http = "0.5"
base64 = "0.6"
rand = "0.3"
two-lock-queue = "0.1"
num_cpus = "1.7"
time = "0.1"
quick-xml = "0.9"
locale = "0.2"
reqwest = "0.8"
chrono = "0.4"
ascii = "0.7"
futures = "0.1"
mime_multipart = "0.5"

[dependencies.mysql]
version = "12.0"
features = ["ssl"]

[dependencies.multipart]
version = "0.14"
features = ["tiny_http", "server"]
