[package]
name = "picture_vault"
version = "0.1.0"
authors = ["Baschdl578 <remailer1@yahoo.de>"]

[dependencies]
image = "0.17"
rexiv2 = "0.5"
lazy_static = "1.0"
base64 = "0.6"
rand = "0.3"
two-lock-queue = "0.1"
num_cpus = "1.7"
time = "0.1"
quick-xml = "0.9"
locale = "0.2"
chrono = "0.4"
ascii = "0.7"
actix-web = "0.3"

[dependencies.mysql]
version = "12.0"
features = ["ssl"]
